{
  "openapi": "3.0.0",
  "info": {
    "title": "[Practica2 - PHP] Users-Results REST API",
    "description": "[Practica2 - PHP] Users-Results REST API operations",
    "license": {
      "name": "MIT License",
      "url": "https://opensource.org/licenses/MIT"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns all users",
        "description": "Returns all users from the system.",
        "operationId": "api_user_getAll",
        "responses": {
          "200": {
            "description": "User array response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UsersArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Creates a new user",
        "description": "Creates a new user",
        "operationId": "api_user_post",
        "responses": {
          "201": {
            "description": "User created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "`Bad Request` Username or email already exists.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          },
          "422": {
            "description": "`Unprocessable entity` Username, e-mail, enabled or password is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserDto"
              }
            }
          },
          "description": "`User` properties to add to the system",
          "required": true
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Deletes all users",
        "description": "Deletes all users ",
        "operationId": "api_user_deleteAll",
        "responses": {
          "204": {
            "description": "Users deleted"
          }
        }
      },
      "options": {
        "tags": [
          "Users"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "api_user_optionsAll",
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a user based on a single ID",
        "description": "Returns the user by `userId`.",
        "operationId": "api_user_getOne",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "User",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Updates a user",
        "description": "Updates the user by `userId`.",
        "operationId": "api_user_put",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "`Content Returned` User previously existed and is now updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "`Bad Request` User name or e-mail already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          },
          "422": {
            "description": "`Unprocessable entity` Username, e-mail, enabled or password is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserDto"
              }
            }
          },
          "description": "`User` data to update",
          "required": true
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Deletes a user",
        "description": "Deletes the user by `userId`.",
        "operationId": "api_user_deleteOne",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "204": {
            "description": "User deleted"
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "options": {
        "tags": [
          "Users"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "api_user_optionsOne",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/results": {
      "get": {
        "tags": [
          "Results"
        ],
        "summary": "Returns all results",
        "description": "Returns all results from the system.",
        "operationId": "api_result_getAll",
        "responses": {
          "200": {
            "description": "Result array response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResultsArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "post": {
        "tags": [
          "Results"
        ],
        "summary": "Creates a new result",
        "description": "Creates a new result",
        "operationId": "api_result_post",
        "responses": {
          "201": {
            "description": "Result created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Result"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          },
          "422": {
            "description": "`Unprocessable entity` Result or user is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResultDto"
              }
            }
          },
          "description": "`Result` properties to add to the system",
          "required": true
        }
      },
      "delete": {
        "tags": [
          "Results"
        ],
        "summary": "Deletes all results",
        "description": "Deletes all results ",
        "operationId": "api_result_deleteAll",
        "responses": {
          "204": {
            "description": "Results deleted"
          }
        }
      },
      "options": {
        "tags": [
          "Results"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "api_result_optionsAll",
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/results/{resultId}": {
      "get": {
        "tags": [
          "Results"
        ],
        "summary": "Returns a result based on a single ID",
        "description": "Returns the result by `resultId`.",
        "operationId": "api_result_getOne",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "200": {
            "description": "Result",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Result"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "put": {
        "tags": [
          "Results"
        ],
        "summary": "Updates a result",
        "description": "Updates the result by `resultId`.",
        "operationId": "api_result_put",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "200": {
            "description": "`Content Returned` Result previously existed and is now updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Result"
                }
              }
            }
          },
          "422": {
            "description": "`Unprocessable entity` Result or user is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResultDto"
              }
            }
          },
          "description": "`Result` data to update",
          "required": true
        }
      },
      "delete": {
        "tags": [
          "Results"
        ],
        "summary": "Deletes a result",
        "description": "Deletes the result by `resultId`.",
        "operationId": "api_result_deleteOne",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "204": {
            "description": "Result deleted"
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "options": {
        "tags": [
          "Results"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "api_result_optionsOne",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/results": {
      "get": {
        "tags": [
          "UserResults"
        ],
        "parameters":[
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "summary": "Returns all results of one user.",
        "description": "Returns all results from the `userId`.",
        "operationId": "api_user_result_getAll",
        "responses": {
          "200": {
            "description": "Result array response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResultsArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "delete": {
        "tags": [
          "UserResults"
        ],
        "parameters":[
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "summary": "Delete all results of one user.",
        "description": "Delete all results from the `userId`.",
        "operationId": "api_user_result_deleteAll",
        "responses": {
          "204": {
            "description": "Result deleted"
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "options": {
        "tags": [
          "UserResults"
        ],
        "parameters":[
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "api_user_result_options",
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Users",
      "description": "Users management"
    },
    {
      "name": "UserResults",
      "description": "Results of one user management"
    },
    {
      "name": "Results",
      "description": "Results management"
    },
  ],
  "servers": [
    {
      "url": "http://127.0.0.1:8000/api/v1"
    }
  ],
  "components": {
    "parameters": {
      "userId": {
        "name": "userId",
        "in": "path",
        "description": "ID of user",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      },
      "resultId": {
        "name": "resultId",
        "in": "path",
        "description": "ID of result",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "responses": {
      "401_Unauthorized_Response": {
        "description": "`Unauthorized` invalid `token` header",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      },
      "403_Forbidden_Response": {
        "description": "`Forbidden` You don't have permission to access",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      },
      "404_Resource_Not_Found_Response": {
        "description": "`Not found` resource not found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      }
    },
    "schemas": {
      "User": {
        "required": [
          "username",
          "email",
          "enabled",
          "password"
        ],
        "properties": {
          "id": {
            "description": "User Id",
            "type": "integer",
            "format": "int32"
          },
          "username": {
            "description": "User name",
            "type": "string"
          },
          "email": {
            "description": "User email",
            "type": "string"
          },
          "enabled": {
            "description": "Denotes if user is enabled",
            "type": "boolean"
          },
          "admin": {
            "description": "Denotes if user has admin privileges",
            "type": "boolean"
          }
        },
        "example": {
          "id": 1508,
          "username": "User name",
          "email": "User email",
          "enabled": true,
          "admin": false
        }
      },
      "UserDto": {
        "required": [
          "username",
          "email",
          "enabled",
          "password"
        ],
        "properties": {
          "username": {
            "description": "User name",
            "type": "string"
          },
          "email": {
            "description": "User email",
            "type": "string"
          },
          "enabled": {
            "description": "Denotes if user is enabled",
            "type": "boolean"
          },
          "admin": {
            "description": "Denotes if user has admin privileges",
            "type": "boolean"
          },
          "password": {
            "description": "User password",
            "type": "string"
          }
        },
        "example": {
          "username": "User name",
          "email": "User email",
          "enabled": true,
          "admin": false,
          "password": "1z2b3c$%&--"
        }
      },
      "UsersArray": {
        "properties": {
          "users": {
            "description": "Users array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/User"
            }
          }
        }
      },
      "Result": {
        "required": [
          "user",
          "result"
        ],
        "properties": {
          "id": {
            "description": "Result Id",
            "type": "integer",
            "format": "int32"
          },
          "result": {
            "description": "Result",
            "type": "integer"
          },
          "user": {
            "description": "User object",
            "type": "object"
          },
          "time": {
            "description": "Creation time",
            "type": "string"
          }
        },
        "example": {
          "id": 8510,
          "result": 12,
          "user": {
            "id": 1508,
            "username": "User name",
            "email": "User email",
            "enabled": true,
            "admin": false,
            "password": "a1b2c3%$&-"
          },
          "time": "2018-12-23 12:19:00"
        }
      },
      "ResultDto": {
        "required": [
          "user",
          "result"
        ],
        "properties": {
          "result": {
            "description": "Result",
            "type": "integer"
          },
          "user": {
            "description": "User object",
            "type": "object"
          }
        },
        "example": {
          "result": 12,
          "user": {
            "id": 1508,
            "username": "User name",
            "email": "User email",
            "enabled": true,
            "admin": false,
            "password": "a1b2c3%$&-"
          }
        }
      },
      "ResultsArray": {
        "properties": {
          "results": {
            "description": "Results array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Result"
            }
          }
        }
      },
      "Message": {
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "description": "Response code",
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "description": "Response message",
            "type": "string"
          }
        },
        "example": {
          "message": {
            "code": "HTTP code",
            "message": "Response Message"
          }
        }
      }
    }
  }
}